openapi: 3.0.3
info:
  description: 'You can use Spotify''s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.


    In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.


    The base URI for all Web API requests is `https://api.spotify.com/v1`.


    Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

    '
  version: 1.0.0
  title: Spotify Web Albums Player API
  termsOfService: https://developer.spotify.com/terms/
  contact:
    name: Spotify for Developers Community
    url: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
servers:
- url: https://api.spotify.com/v1
tags:
- name: Player
paths:
  /me/player:
    get:
      tags:
      - Player
      operationId: get-information-about-the-users-current-playback
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      summary: 'Get Playback State

        '
      description: 'Get information about the user’s current playback state, including track or episode, progress, and active device.

        '
      security:
      - oauth_2_0:
        - user-read-playback-state
    put:
      tags:
      - Player
      operationId: transfer-a-users-playback
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      summary: 'Transfer Playback

        '
      description: 'Transfer playback to a new device and optionally begin playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.

        '
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/devices:
    get:
      tags:
      - Player
      operationId: get-a-users-available-devices
      summary: 'Get Available Devices

        '
      description: 'Get information about a user’s available Spotify Connect devices. Some device models are not supported and will not be listed in the API response.

        '
      security:
      - oauth_2_0:
        - user-read-playback-state
  /me/player/currently-playing:
    get:
      tags:
      - Player
      operationId: get-the-users-currently-playing-track
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      summary: 'Get Currently Playing Track

        '
      description: 'Get the object currently being played on the user''s Spotify account.

        '
      security:
      - oauth_2_0:
        - user-read-currently-playing
  /me/player/play:
    put:
      tags:
      - Player
      operationId: start-a-users-playback
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      summary: 'Start/Resume Playback

        '
      description: 'Start a new context or resume current playback on the user''s active device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.

        '
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/pause:
    put:
      tags:
      - Player
      operationId: pause-a-users-playback
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      summary: 'Pause Playback

        '
      description: 'Pause playback on the user''s account. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.

        '
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/next:
    post:
      tags:
      - Player
      operationId: skip-users-playback-to-next-track
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      summary: 'Skip To Next

        '
      description: 'Skips to next track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.

        '
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/previous:
    post:
      tags:
      - Player
      operationId: skip-users-playback-to-previous-track
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      summary: 'Skip To Previous

        '
      description: 'Skips to previous track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.

        '
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/seek:
    put:
      tags:
      - Player
      operationId: seek-to-position-in-currently-playing-track
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      summary: 'Seek To Position

        '
      description: 'Seeks to the given position in the user’s currently playing track. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.

        '
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/repeat:
    put:
      tags:
      - Player
      operationId: set-repeat-mode-on-users-playback
      summary: 'Set Repeat Mode

        '
      description: 'Set the repeat mode for the user''s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.

        '
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/volume:
    put:
      tags:
      - Player
      operationId: set-volume-for-users-playback
      summary: 'Set Playback Volume

        '
      description: 'Set the volume for the user’s current playback device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.

        '
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/shuffle:
    put:
      tags:
      - Player
      operationId: toggle-shuffle-for-users-playback
      summary: 'Toggle Playback Shuffle

        '
      description: 'Toggle shuffle on or off for user’s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.

        '
      security:
      - oauth_2_0:
        - user-modify-playback-state
  /me/player/recently-played:
    get:
      tags:
      - Player
      operationId: get-recently-played
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      summary: 'Get Recently Played Tracks

        '
      description: 'Get tracks from the current user''s recently played tracks.

        _**Note**: Currently doesn''t support podcast episodes._

        '
      security:
      - oauth_2_0:
        - user-read-recently-played
  /me/player/queue:
    get:
      tags:
      - Player
      operationId: get-queue
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      summary: 'Get the User''s Queue

        '
      description: 'Get the list of objects that make up the user''s queue.

        '
      security:
      - oauth_2_0:
        - user-read-currently-playing
        - user-read-playback-state
    post:
      tags:
      - Player
      operationId: add-to-queue
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/playerPolicyList'
      summary: 'Add Item to Playback Queue

        '
      description: 'Add an item to be played next in the user''s current playback queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.

        '
      security:
      - oauth_2_0:
        - user-modify-playback-state
components:
  x-spotify-policy:
    playerPolicyList:
    - $ref: '#/components/x-spotify-policy/policies/CommercialStreaming'
    - $ref: '#/components/x-spotify-policy/policies/ContentAlteration'
    - $ref: '#/components/x-spotify-policy/policies/Synchronization'
    - $ref: '#/components/x-spotify-policy/policies/Broadcasting'
  securitySchemes:
    oauth_2_0:
      type: oauth2
      description: Spotify supports OAuth 2.0 for authenticating all API requests.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          tokenUrl: https://accounts.spotify.com/api/token
          scopes:
            app-remote-control: 'Communicate with the Spotify app on your device.

              '
            playlist-read-private: 'Access your private playlists.

              '
            playlist-read-collaborative: 'Access your collaborative playlists.

              '
            playlist-modify-public: 'Manage your public playlists.

              '
            playlist-modify-private: 'Manage your private playlists.

              '
            user-library-read: 'Access your saved content.

              '
            user-library-modify: 'Manage your saved content.

              '
            user-read-private: 'Access your subscription details.

              '
            user-read-email: 'Get your real email address.

              '
            user-follow-read: 'Access your followers and who you are following.

              '
            user-follow-modify: 'Manage your saved content.

              '
            user-top-read: 'Read your top artists and content.

              '
            user-read-playback-position: 'Read your position in content you have played.

              '
            user-read-playback-state: 'Read your currently playing content and Spotify Connect devices information.

              '
            user-read-recently-played: 'Access your recently played items.

              '
            user-read-currently-playing: 'Read your currently playing content.

              '
            user-modify-playback-state: 'Control playback on your Spotify clients and Spotify Connect devices.

              '
            ugc-image-upload: 'Upload images to Spotify on your behalf.

              '
            streaming: 'Play content and control playback on your other devices.

              '
