openapi: 3.0.3
info:
  description: 'You can use Spotify''s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.


    In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.


    The base URI for all Web API requests is `https://api.spotify.com/v1`.


    Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

    '
  version: 1.0.0
  title: Spotify Web Albums Tracks API
  termsOfService: https://developer.spotify.com/terms/
  contact:
    name: Spotify for Developers Community
    url: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
servers:
- url: https://api.spotify.com/v1
tags:
- name: Tracks
paths:
  /albums/{id}/tracks:
    get:
      operationId: get-an-albums-tracks
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      tags:
      - Tracks
      summary: 'Get Album Tracks

        '
      description: 'Get Spotify catalog information about an album’s tracks.

        Optional parameters can be used to limit the number of tracks returned.

        '
      security:
      - oauth_2_0: []
  /artists/{id}/top-tracks:
    get:
      deprecated: true
      tags:
      - Tracks
      operationId: get-an-artists-top-tracks
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      summary: 'Get Artist''s Top Tracks

        '
      description: 'Get Spotify catalog information about an artist''s top tracks by country.

        '
      security:
      - oauth_2_0: []
  /tracks/{id}:
    get:
      tags:
      - Tracks
      operationId: get-track
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      summary: 'Get Track

        '
      description: 'Get Spotify catalog information for a single track identified by its

        unique Spotify ID.

        '
      security:
      - oauth_2_0: []
  /tracks:
    get:
      deprecated: true
      tags:
      - Tracks
      operationId: get-several-tracks
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      summary: 'Get Several Tracks

        '
      description: 'Get Spotify catalog information for multiple tracks based on their Spotify IDs.

        '
      security:
      - oauth_2_0: []
  /playlists/{playlist_id}/tracks:
    get:
      tags:
      - Tracks
      operationId: get-playlists-tracks
      deprecated: true
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      summary: 'Get Playlist Items [DEPRECATED]

        '
      description: '**Deprecated:** Use [Get Playlist Items](/documentation/web-api/reference/get-playlists-items) instead.


        Get full details of the items of a playlist owned by a Spotify user.

        '
      security:
      - oauth_2_0:
        - playlist-read-private
    post:
      tags:
      - Tracks
      operationId: add-tracks-to-playlist
      deprecated: true
      summary: 'Add Items to Playlist [DEPRECATED]

        '
      description: '**Deprecated:** Use [Add Items to Playlist](/documentation/web-api/reference/add-items-to-playlist) instead.


        Add one or more items to a user''s playlist.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    put:
      tags:
      - Tracks
      operationId: reorder-or-replace-playlists-tracks
      deprecated: true
      summary: 'Update Playlist Items [DEPRECATED]

        '
      description: '**Deprecated:** Use [Update Playlist Items](/documentation/web-api/reference/reorder-or-replace-playlists-items) instead.


        Either reorder or replace items in a playlist depending on the request''s parameters.

        To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request''s body.

        To replace items, include `uris` as either a query parameter or in the request''s body.

        Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.

        <br/>

        **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters.

        These operations can''t be applied together in a single request.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    delete:
      tags:
      - Tracks
      operationId: remove-tracks-playlist
      deprecated: true
      summary: 'Remove Playlist Items [DEPRECATED]

        '
      description: '**Deprecated:** Use [Remove Playlist Items](/documentation/web-api/reference/remove-items-playlist) instead.


        Remove one or more items from a user''s playlist.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /playlists/{playlist_id}/items:
    get:
      tags:
      - Tracks
      operationId: get-playlists-items
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      summary: 'Get Playlist Items

        '
      description: 'Get full details of the items of a playlist owned by a Spotify user.


        **Note**: This endpoint is only accessible for playlists owned by the current user or playlists the user is a collaborator of. A `403 Forbidden` status code will be returned if the user is neither the owner nor a collaborator of the playlist.

        '
      security:
      - oauth_2_0:
        - playlist-read-private
    post:
      tags:
      - Tracks
      operationId: add-items-to-playlist
      summary: 'Add Items to Playlist

        '
      description: 'Add one or more items to a user''s playlist.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    put:
      tags:
      - Tracks
      operationId: reorder-or-replace-playlists-items
      summary: 'Update Playlist Items

        '
      description: 'Either reorder or replace items in a playlist depending on the request''s parameters.

        To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request''s body.

        To replace items, include `uris` as either a query parameter or in the request''s body.

        Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.

        <br/>

        **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters.

        These operations can''t be applied together in a single request.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    delete:
      tags:
      - Tracks
      operationId: remove-items-playlist
      summary: 'Remove Playlist Items

        '
      description: 'Remove one or more items from a user''s playlist.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /me/tracks:
    get:
      tags:
      - Tracks
      operationId: get-users-saved-tracks
      summary: 'Get User''s Saved Tracks

        '
      description: 'Get a list of the songs saved in the current Spotify user''s ''Your Music'' library.

        '
      security:
      - oauth_2_0:
        - user-library-read
    put:
      deprecated: true
      tags:
      - Tracks
      operationId: save-tracks-user
      summary: 'Save Tracks for Current User

        '
      description: 'Save one or more tracks to the current user''s ''Your Music'' library.


        **Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      deprecated: true
      tags:
      - Tracks
      operationId: remove-tracks-user
      summary: 'Remove User''s Saved Tracks

        '
      description: 'Remove one or more tracks from the current user''s ''Your Music'' library.


        **Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
  /me/tracks/contains:
    get:
      tags:
      - Tracks
      operationId: check-users-saved-tracks
      summary: 'Check User''s Saved Tracks

        '
      deprecated: true
      description: 'Check if one or more tracks is already saved in the current Spotify user''s ''Your Music'' library.


        **Note:** This endpoint is deprecated. Use [Check User''s Saved Items](/documentation/web-api/reference/check-library-contains) instead.

        '
      security:
      - oauth_2_0:
        - user-library-read
  /me/top/{type}:
    get:
      tags:
      - Tracks
      operationId: get-users-top-artists-and-tracks
      summary: 'Get User''s Top Items

        '
      description: 'Get the current user''s top artists or tracks based on calculated affinity.

        '
      security:
      - oauth_2_0:
        - user-top-read
  /audio-features:
    get:
      deprecated: true
      tags:
      - Tracks
      operationId: get-several-audio-features
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
      summary: 'Get Several Tracks'' Audio Features

        '
      description: 'Get audio features for multiple tracks based on their Spotify IDs.

        '
      security:
      - oauth_2_0: []
  /audio-features/{id}:
    get:
      deprecated: true
      tags:
      - Tracks
      operationId: get-audio-features
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
      summary: 'Get Track''s Audio Features

        '
      description: 'Get audio feature information for a single track identified by its unique

        Spotify ID.

        '
      security:
      - oauth_2_0: []
  /audio-analysis/{id}:
    get:
      deprecated: true
      tags:
      - Tracks
      operationId: get-audio-analysis
      summary: 'Get Track''s Audio Analysis

        '
      description: 'Get a low-level audio analysis for a track in the Spotify catalog. The audio analysis describes the track’s structure and musical content, including rhythm, pitch, and timbre.

        '
      security:
      - oauth_2_0: []
  /recommendations:
    get:
      deprecated: true
      tags:
      - Tracks
      operationId: get-recommendations
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
      summary: 'Get Recommendations

        '
      description: 'Recommendations are generated based on the available information for a given seed entity and matched against similar artists and tracks. If there is sufficient information about the provided seeds, a list of tracks will be returned together with pool size details.


        For artists and tracks that are very new or obscure there might not be enough data to generate a list of tracks.

        '
      security:
      - oauth_2_0: []
components:
  x-spotify-policy:
    metadataPolicyList:
    - $ref: '#/components/x-spotify-policy/policies/Downloading'
    - $ref: '#/components/x-spotify-policy/policies/VisualAlteration'
    - $ref: '#/components/x-spotify-policy/policies/Attribution'
    metadataWithMachineLearningPolicyList:
    - $ref: '#/components/x-spotify-policy/policies/Downloading'
    - $ref: '#/components/x-spotify-policy/policies/VisualAlteration'
    - $ref: '#/components/x-spotify-policy/policies/Attribution'
    - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
  securitySchemes:
    oauth_2_0:
      type: oauth2
      description: Spotify supports OAuth 2.0 for authenticating all API requests.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          tokenUrl: https://accounts.spotify.com/api/token
          scopes:
            app-remote-control: 'Communicate with the Spotify app on your device.

              '
            playlist-read-private: 'Access your private playlists.

              '
            playlist-read-collaborative: 'Access your collaborative playlists.

              '
            playlist-modify-public: 'Manage your public playlists.

              '
            playlist-modify-private: 'Manage your private playlists.

              '
            user-library-read: 'Access your saved content.

              '
            user-library-modify: 'Manage your saved content.

              '
            user-read-private: 'Access your subscription details.

              '
            user-read-email: 'Get your real email address.

              '
            user-follow-read: 'Access your followers and who you are following.

              '
            user-follow-modify: 'Manage your saved content.

              '
            user-top-read: 'Read your top artists and content.

              '
            user-read-playback-position: 'Read your position in content you have played.

              '
            user-read-playback-state: 'Read your currently playing content and Spotify Connect devices information.

              '
            user-read-recently-played: 'Access your recently played items.

              '
            user-read-currently-playing: 'Read your currently playing content.

              '
            user-modify-playback-state: 'Control playback on your Spotify clients and Spotify Connect devices.

              '
            ugc-image-upload: 'Upload images to Spotify on your behalf.

              '
            streaming: 'Play content and control playback on your other devices.

              '
