openapi: 3.0.3
info:
  description: 'You can use Spotify''s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.


    In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.


    The base URI for all Web API requests is `https://api.spotify.com/v1`.


    Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

    '
  version: 1.0.0
  title: Spotify Web Albums Library API
  termsOfService: https://developer.spotify.com/terms/
  contact:
    name: Spotify for Developers Community
    url: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
servers:
- url: https://api.spotify.com/v1
tags:
- name: Library
paths:
  /me/audiobooks:
    get:
      tags:
      - Library
      operationId: get-users-saved-audiobooks
      summary: 'Get User''s Saved Audiobooks

        '
      description: 'Get a list of the audiobooks saved in the current Spotify user''s ''Your Music'' library.

        '
      security:
      - oauth_2_0:
        - user-library-read
    put:
      deprecated: true
      tags:
      - Library
      operationId: save-audiobooks-user
      summary: 'Save Audiobooks for Current User

        '
      description: 'Save one or more audiobooks to the current Spotify user''s library.


        **Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      deprecated: true
      tags:
      - Library
      operationId: remove-audiobooks-user
      summary: 'Remove User''s Saved Audiobooks

        '
      description: 'Remove one or more audiobooks from the Spotify user''s library.


        **Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
  /me/audiobooks/contains:
    get:
      tags:
      - Library
      operationId: check-users-saved-audiobooks
      summary: 'Check User''s Saved Audiobooks

        '
      deprecated: true
      description: 'Check if one or more audiobooks are already saved in the current Spotify user''s library.


        **Note:** This endpoint is deprecated. Use [Check User''s Saved Items](/documentation/web-api/reference/check-library-contains) instead.

        '
      security:
      - oauth_2_0:
        - user-library-read
  /playlists/{playlist_id}:
    put:
      tags:
      - Library
      operationId: change-playlist-details
      summary: 'Change Playlist Details

        '
      description: 'Change a playlist''s name and public/private state. (The user must, of

        course, own the playlist.)

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /me/playlists:
    get:
      tags:
      - Library
      operationId: get-a-list-of-current-users-playlists
      summary: 'Get Current User''s Playlists

        '
      description: 'Get a list of the playlists owned or followed by the current Spotify

        user.

        '
      security:
      - oauth_2_0:
        - playlist-read-private
    post:
      tags:
      - Library
      operationId: create-playlist
      summary: 'Create Playlist

        '
      description: 'Create a playlist for the current Spotify user. (The playlist will be empty until

        you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)

        Each user is generally limited to a maximum of 11000 playlists.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /me/library:
    put:
      tags:
      - Library
      operationId: save-library-items
      summary: 'Save Items to Library

        '
      description: 'Add one or more items to the current user''s library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, users, and playlists.

        '
      security:
      - oauth_2_0:
        - user-library-modify
        - user-follow-modify
        - playlist-modify-public
    delete:
      tags:
      - Library
      operationId: remove-library-items
      summary: 'Remove Items from Library

        '
      description: 'Remove one or more items from the current user''s library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, users, and playlists.

        '
      security:
      - oauth_2_0:
        - user-library-modify
        - user-follow-modify
        - playlist-modify-public
  /me/library/contains:
    get:
      tags:
      - Library
      operationId: check-library-contains
      summary: 'Check User''s Saved Items

        '
      description: 'Check if one or more items are already saved in the current user''s library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, artists, users, and playlists.

        '
      security:
      - oauth_2_0:
        - user-library-read
        - user-follow-read
        - playlist-read-private
  /me/albums:
    get:
      tags:
      - Library
      operationId: get-users-saved-albums
      summary: 'Get User''s Saved Albums

        '
      description: 'Get a list of the albums saved in the current Spotify user''s ''Your Music'' library.

        '
      security:
      - oauth_2_0:
        - user-library-read
    put:
      deprecated: true
      tags:
      - Library
      operationId: save-albums-user
      summary: 'Save Albums for Current User

        '
      description: 'Save one or more albums to the current user''s ''Your Music'' library.


        **Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      deprecated: true
      tags:
      - Library
      operationId: remove-albums-user
      summary: 'Remove Users'' Saved Albums

        '
      description: 'Remove one or more albums from the current user''s ''Your Music'' library.


        **Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
  /me/albums/contains:
    get:
      tags:
      - Library
      operationId: check-users-saved-albums
      summary: 'Check User''s Saved Albums

        '
      deprecated: true
      description: 'Check if one or more albums is already saved in the current Spotify user''s ''Your Music'' library.


        **Note:** This endpoint is deprecated. Use [Check User''s Saved Items](/documentation/web-api/reference/check-library-contains) instead.

        '
      security:
      - oauth_2_0:
        - user-library-read
  /me/tracks:
    get:
      tags:
      - Library
      operationId: get-users-saved-tracks
      summary: 'Get User''s Saved Tracks

        '
      description: 'Get a list of the songs saved in the current Spotify user''s ''Your Music'' library.

        '
      security:
      - oauth_2_0:
        - user-library-read
    put:
      deprecated: true
      tags:
      - Library
      operationId: save-tracks-user
      summary: 'Save Tracks for Current User

        '
      description: 'Save one or more tracks to the current user''s ''Your Music'' library.


        **Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      deprecated: true
      tags:
      - Library
      operationId: remove-tracks-user
      summary: 'Remove User''s Saved Tracks

        '
      description: 'Remove one or more tracks from the current user''s ''Your Music'' library.


        **Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
  /me/tracks/contains:
    get:
      tags:
      - Library
      operationId: check-users-saved-tracks
      summary: 'Check User''s Saved Tracks

        '
      deprecated: true
      description: 'Check if one or more tracks is already saved in the current Spotify user''s ''Your Music'' library.


        **Note:** This endpoint is deprecated. Use [Check User''s Saved Items](/documentation/web-api/reference/check-library-contains) instead.

        '
      security:
      - oauth_2_0:
        - user-library-read
  /me/episodes:
    get:
      tags:
      - Library
      operationId: get-users-saved-episodes
      summary: 'Get User''s Saved Episodes

        '
      description: 'Get a list of the episodes saved in the current Spotify user''s library.

        '
      security:
      - oauth_2_0:
        - user-library-read
        - user-read-playback-position
    put:
      deprecated: true
      tags:
      - Library
      operationId: save-episodes-user
      summary: 'Save Episodes for Current User

        '
      description: 'Save one or more episodes to the current user''s library.


        **Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      deprecated: true
      tags:
      - Library
      operationId: remove-episodes-user
      summary: 'Remove User''s Saved Episodes

        '
      description: 'Remove one or more episodes from the current user''s library.


        **Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
  /me/episodes/contains:
    get:
      tags:
      - Library
      operationId: check-users-saved-episodes
      summary: 'Check User''s Saved Episodes

        '
      deprecated: true
      description: 'Check if one or more episodes is already saved in the current Spotify user''s ''Your Episodes'' library.


        **Note:** This endpoint is deprecated. Use [Check User''s Saved Items](/documentation/web-api/reference/check-library-contains) instead.

        '
      security:
      - oauth_2_0:
        - user-library-read
  /me/shows:
    get:
      tags:
      - Library
      operationId: get-users-saved-shows
      summary: 'Get User''s Saved Shows

        '
      description: 'Get a list of shows saved in the current Spotify user''s library. Optional parameters can be used to limit the number of shows returned.

        '
      security:
      - oauth_2_0:
        - user-library-read
    put:
      deprecated: true
      tags:
      - Library
      operationId: save-shows-user
      summary: 'Save Shows for Current User

        '
      description: 'Save one or more shows to current Spotify user''s library.


        **Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      deprecated: true
      tags:
      - Library
      operationId: remove-shows-user
      summary: 'Remove User''s Saved Shows

        '
      description: 'Delete one or more shows from current Spotify user''s library.


        **Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
  /me/shows/contains:
    get:
      tags:
      - Library
      operationId: check-users-saved-shows
      summary: 'Check User''s Saved Shows

        '
      deprecated: true
      description: 'Check if one or more shows is already saved in the current Spotify user''s library.


        **Note:** This endpoint is deprecated. Use [Check User''s Saved Items](/documentation/web-api/reference/check-library-contains) instead.

        '
      security:
      - oauth_2_0:
        - user-library-read
  /me/top/{type}:
    get:
      tags:
      - Library
      operationId: get-users-top-artists-and-tracks
      summary: 'Get User''s Top Items

        '
      description: 'Get the current user''s top artists or tracks based on calculated affinity.

        '
      security:
      - oauth_2_0:
        - user-top-read
  /users/{user_id}/playlists:
    post:
      tags:
      - Library
      operationId: create-playlist-for-user
      deprecated: true
      summary: 'Create Playlist for user

        '
      description: '**Deprecated**: Use [Create Playlist](/documentation/web-api/reference/create-playlist) instead.


        Create a playlist for a Spotify user. (The playlist will be empty until

        you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)

        Each user is generally limited to a maximum of 11000 playlists.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /me/following:
    get:
      tags:
      - Library
      operationId: get-followed
      summary: 'Get Followed Artists

        '
      description: 'Get the current user''s followed artists.

        '
      security:
      - oauth_2_0:
        - user-follow-read
    put:
      deprecated: true
      tags:
      - Library
      operationId: follow-artists-users
      summary: 'Follow Artists or Users

        '
      description: 'Add the current user as a follower of one or more artists or other Spotify users.


        **Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-follow-modify
    delete:
      deprecated: true
      tags:
      - Library
      operationId: unfollow-artists-users
      summary: 'Unfollow Artists or Users

        '
      description: 'Remove the current user as a follower of one or more artists or other Spotify users.


        **Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-follow-modify
  /me/following/contains:
    get:
      tags:
      - Library
      operationId: check-current-user-follows
      summary: 'Check If User Follows Artists or Users

        '
      deprecated: true
      description: 'Check to see if the current user is following one or more artists or other Spotify users.


        **Note:** This endpoint is deprecated. Use [Check User''s Saved Items](/documentation/web-api/reference/check-library-contains) instead.

        '
      security:
      - oauth_2_0:
        - user-follow-read
components:
  securitySchemes:
    oauth_2_0:
      type: oauth2
      description: Spotify supports OAuth 2.0 for authenticating all API requests.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          tokenUrl: https://accounts.spotify.com/api/token
          scopes:
            app-remote-control: 'Communicate with the Spotify app on your device.

              '
            playlist-read-private: 'Access your private playlists.

              '
            playlist-read-collaborative: 'Access your collaborative playlists.

              '
            playlist-modify-public: 'Manage your public playlists.

              '
            playlist-modify-private: 'Manage your private playlists.

              '
            user-library-read: 'Access your saved content.

              '
            user-library-modify: 'Manage your saved content.

              '
            user-read-private: 'Access your subscription details.

              '
            user-read-email: 'Get your real email address.

              '
            user-follow-read: 'Access your followers and who you are following.

              '
            user-follow-modify: 'Manage your saved content.

              '
            user-top-read: 'Read your top artists and content.

              '
            user-read-playback-position: 'Read your position in content you have played.

              '
            user-read-playback-state: 'Read your currently playing content and Spotify Connect devices information.

              '
            user-read-recently-played: 'Access your recently played items.

              '
            user-read-currently-playing: 'Read your currently playing content.

              '
            user-modify-playback-state: 'Control playback on your Spotify clients and Spotify Connect devices.

              '
            ugc-image-upload: 'Upload images to Spotify on your behalf.

              '
            streaming: 'Play content and control playback on your other devices.

              '
