openapi: 3.0.3
info:
  description: 'You can use Spotify''s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.


    In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.


    The base URI for all Web API requests is `https://api.spotify.com/v1`.


    Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

    '
  version: 1.0.0
  title: Spotify Web Albums Playlists API
  termsOfService: https://developer.spotify.com/terms/
  contact:
    name: Spotify for Developers Community
    url: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
servers:
- url: https://api.spotify.com/v1
tags:
- name: Playlists
paths:
  /playlists/{playlist_id}:
    get:
      tags:
      - Playlists
      operationId: get-playlist
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      summary: 'Get Playlist

        '
      description: 'Get a playlist owned by a Spotify user.

        '
      security:
      - oauth_2_0: []
    put:
      tags:
      - Playlists
      operationId: change-playlist-details
      summary: 'Change Playlist Details

        '
      description: 'Change a playlist''s name and public/private state. (The user must, of

        course, own the playlist.)

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /playlists/{playlist_id}/tracks:
    get:
      tags:
      - Playlists
      operationId: get-playlists-tracks
      deprecated: true
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      summary: 'Get Playlist Items [DEPRECATED]

        '
      description: '**Deprecated:** Use [Get Playlist Items](/documentation/web-api/reference/get-playlists-items) instead.


        Get full details of the items of a playlist owned by a Spotify user.

        '
      security:
      - oauth_2_0:
        - playlist-read-private
    post:
      tags:
      - Playlists
      operationId: add-tracks-to-playlist
      deprecated: true
      summary: 'Add Items to Playlist [DEPRECATED]

        '
      description: '**Deprecated:** Use [Add Items to Playlist](/documentation/web-api/reference/add-items-to-playlist) instead.


        Add one or more items to a user''s playlist.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    put:
      tags:
      - Playlists
      operationId: reorder-or-replace-playlists-tracks
      deprecated: true
      summary: 'Update Playlist Items [DEPRECATED]

        '
      description: '**Deprecated:** Use [Update Playlist Items](/documentation/web-api/reference/reorder-or-replace-playlists-items) instead.


        Either reorder or replace items in a playlist depending on the request''s parameters.

        To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request''s body.

        To replace items, include `uris` as either a query parameter or in the request''s body.

        Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.

        <br/>

        **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters.

        These operations can''t be applied together in a single request.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    delete:
      tags:
      - Playlists
      operationId: remove-tracks-playlist
      deprecated: true
      summary: 'Remove Playlist Items [DEPRECATED]

        '
      description: '**Deprecated:** Use [Remove Playlist Items](/documentation/web-api/reference/remove-items-playlist) instead.


        Remove one or more items from a user''s playlist.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /playlists/{playlist_id}/items:
    get:
      tags:
      - Playlists
      operationId: get-playlists-items
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      summary: 'Get Playlist Items

        '
      description: 'Get full details of the items of a playlist owned by a Spotify user.


        **Note**: This endpoint is only accessible for playlists owned by the current user or playlists the user is a collaborator of. A `403 Forbidden` status code will be returned if the user is neither the owner nor a collaborator of the playlist.

        '
      security:
      - oauth_2_0:
        - playlist-read-private
    post:
      tags:
      - Playlists
      operationId: add-items-to-playlist
      summary: 'Add Items to Playlist

        '
      description: 'Add one or more items to a user''s playlist.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    put:
      tags:
      - Playlists
      operationId: reorder-or-replace-playlists-items
      summary: 'Update Playlist Items

        '
      description: 'Either reorder or replace items in a playlist depending on the request''s parameters.

        To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request''s body.

        To replace items, include `uris` as either a query parameter or in the request''s body.

        Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.

        <br/>

        **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters.

        These operations can''t be applied together in a single request.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    delete:
      tags:
      - Playlists
      operationId: remove-items-playlist
      summary: 'Remove Playlist Items

        '
      description: 'Remove one or more items from a user''s playlist.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /me/playlists:
    get:
      tags:
      - Playlists
      operationId: get-a-list-of-current-users-playlists
      summary: 'Get Current User''s Playlists

        '
      description: 'Get a list of the playlists owned or followed by the current Spotify

        user.

        '
      security:
      - oauth_2_0:
        - playlist-read-private
    post:
      tags:
      - Playlists
      operationId: create-playlist
      summary: 'Create Playlist

        '
      description: 'Create a playlist for the current Spotify user. (The playlist will be empty until

        you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)

        Each user is generally limited to a maximum of 11000 playlists.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /users/{user_id}/playlists:
    get:
      deprecated: true
      tags:
      - Playlists
      operationId: get-list-users-playlists
      summary: 'Get User''s Playlists

        '
      description: 'Get a list of the playlists owned or followed by a Spotify user.

        '
      security:
      - oauth_2_0:
        - playlist-read-private
        - playlist-read-collaborative
    post:
      tags:
      - Playlists
      operationId: create-playlist-for-user
      deprecated: true
      summary: 'Create Playlist for user

        '
      description: '**Deprecated**: Use [Create Playlist](/documentation/web-api/reference/create-playlist) instead.


        Create a playlist for a Spotify user. (The playlist will be empty until

        you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)

        Each user is generally limited to a maximum of 11000 playlists.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /playlists/{playlist_id}/followers:
    put:
      deprecated: true
      tags:
      - Playlists
      operationId: follow-playlist
      description: 'Add the current user as a follower of a playlist.


        **Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.

        '
      summary: 'Follow Playlist

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    delete:
      deprecated: true
      tags:
      - Playlists
      operationId: unfollow-playlist
      summary: 'Unfollow Playlist

        '
      description: 'Remove the current user as a follower of a playlist.


        **Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /browse/featured-playlists:
    get:
      deprecated: true
      tags:
      - Playlists
      operationId: get-featured-playlists
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MultipleIntegrations'
      summary: 'Get Featured Playlists

        '
      description: 'Get a list of Spotify featured playlists (shown, for example, on a Spotify player''s ''Browse'' tab).

        '
      security:
      - oauth_2_0: []
  /browse/categories/{category_id}/playlists:
    get:
      deprecated: true
      tags:
      - Playlists
      operationId: get-a-categories-playlists
      summary: 'Get Category''s Playlists

        '
      description: 'Get a list of Spotify playlists tagged with a particular category.

        '
      security:
      - oauth_2_0: []
  /playlists/{playlist_id}/images:
    get:
      tags:
      - Playlists
      operationId: get-playlist-cover
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      summary: 'Get Playlist Cover Image

        '
      description: 'Get the current image associated with a specific playlist.

        '
      security:
      - oauth_2_0: []
    put:
      tags:
      - Playlists
      operationId: upload-custom-playlist-cover
      summary: 'Add Custom Playlist Cover Image

        '
      description: 'Replace the image used to represent a specific playlist.

        '
      security:
      - oauth_2_0:
        - ugc-image-upload
        - playlist-modify-public
        - playlist-modify-private
  /playlists/{playlist_id}/followers/contains:
    get:
      tags:
      - Playlists
      operationId: check-if-user-follows-playlist
      summary: 'Check if Current User Follows Playlist

        '
      deprecated: true
      description: 'Check to see if the current user is following a specified playlist.


        **Note:** This endpoint is deprecated. Use [Check User''s Saved Items](/documentation/web-api/reference/check-library-contains) instead.

        '
      security:
      - oauth_2_0: []
components:
  x-spotify-policy:
    metadataWithMachineLearningPolicyList:
    - $ref: '#/components/x-spotify-policy/policies/Downloading'
    - $ref: '#/components/x-spotify-policy/policies/VisualAlteration'
    - $ref: '#/components/x-spotify-policy/policies/Attribution'
    - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
  securitySchemes:
    oauth_2_0:
      type: oauth2
      description: Spotify supports OAuth 2.0 for authenticating all API requests.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          tokenUrl: https://accounts.spotify.com/api/token
          scopes:
            app-remote-control: 'Communicate with the Spotify app on your device.

              '
            playlist-read-private: 'Access your private playlists.

              '
            playlist-read-collaborative: 'Access your collaborative playlists.

              '
            playlist-modify-public: 'Manage your public playlists.

              '
            playlist-modify-private: 'Manage your private playlists.

              '
            user-library-read: 'Access your saved content.

              '
            user-library-modify: 'Manage your saved content.

              '
            user-read-private: 'Access your subscription details.

              '
            user-read-email: 'Get your real email address.

              '
            user-follow-read: 'Access your followers and who you are following.

              '
            user-follow-modify: 'Manage your saved content.

              '
            user-top-read: 'Read your top artists and content.

              '
            user-read-playback-position: 'Read your position in content you have played.

              '
            user-read-playback-state: 'Read your currently playing content and Spotify Connect devices information.

              '
            user-read-recently-played: 'Access your recently played items.

              '
            user-read-currently-playing: 'Read your currently playing content.

              '
            user-modify-playback-state: 'Control playback on your Spotify clients and Spotify Connect devices.

              '
            ugc-image-upload: 'Upload images to Spotify on your behalf.

              '
            streaming: 'Play content and control playback on your other devices.

              '
