openapi: 3.0.3
info:
  description: 'You can use Spotify''s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.


    In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.


    The base URI for all Web API requests is `https://api.spotify.com/v1`.


    Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

    '
  version: 1.0.0
  title: Spotify Web Albums Users API
  termsOfService: https://developer.spotify.com/terms/
  contact:
    name: Spotify for Developers Community
    url: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
servers:
- url: https://api.spotify.com/v1
tags:
- name: Users
paths:
  /me:
    get:
      tags:
      - Users
      operationId: get-current-users-profile
      summary: 'Get Current User''s Profile

        '
      description: 'Get detailed profile information about the current user (including the

        current user''s username).

        '
      security:
      - oauth_2_0:
        - user-read-private
        - user-read-email
  /me/top/{type}:
    get:
      tags:
      - Users
      operationId: get-users-top-artists-and-tracks
      summary: 'Get User''s Top Items

        '
      description: 'Get the current user''s top artists or tracks based on calculated affinity.

        '
      security:
      - oauth_2_0:
        - user-top-read
  /users/{user_id}:
    get:
      deprecated: true
      tags:
      - Users
      operationId: get-users-profile
      summary: 'Get User''s Profile

        '
      description: 'Get public profile information about a Spotify user.

        '
      security:
      - oauth_2_0: []
  /users/{user_id}/playlists:
    get:
      deprecated: true
      tags:
      - Users
      operationId: get-list-users-playlists
      summary: 'Get User''s Playlists

        '
      description: 'Get a list of the playlists owned or followed by a Spotify user.

        '
      security:
      - oauth_2_0:
        - playlist-read-private
        - playlist-read-collaborative
  /playlists/{playlist_id}/followers:
    put:
      deprecated: true
      tags:
      - Users
      operationId: follow-playlist
      description: 'Add the current user as a follower of a playlist.


        **Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.

        '
      summary: 'Follow Playlist

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
    delete:
      deprecated: true
      tags:
      - Users
      operationId: unfollow-playlist
      summary: 'Unfollow Playlist

        '
      description: 'Remove the current user as a follower of a playlist.


        **Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.

        '
      security:
      - oauth_2_0:
        - playlist-modify-public
        - playlist-modify-private
  /me/following:
    get:
      tags:
      - Users
      operationId: get-followed
      summary: 'Get Followed Artists

        '
      description: 'Get the current user''s followed artists.

        '
      security:
      - oauth_2_0:
        - user-follow-read
    put:
      deprecated: true
      tags:
      - Users
      operationId: follow-artists-users
      summary: 'Follow Artists or Users

        '
      description: 'Add the current user as a follower of one or more artists or other Spotify users.


        **Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-follow-modify
    delete:
      deprecated: true
      tags:
      - Users
      operationId: unfollow-artists-users
      summary: 'Unfollow Artists or Users

        '
      description: 'Remove the current user as a follower of one or more artists or other Spotify users.


        **Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-follow-modify
  /me/following/contains:
    get:
      tags:
      - Users
      operationId: check-current-user-follows
      summary: 'Check If User Follows Artists or Users

        '
      deprecated: true
      description: 'Check to see if the current user is following one or more artists or other Spotify users.


        **Note:** This endpoint is deprecated. Use [Check User''s Saved Items](/documentation/web-api/reference/check-library-contains) instead.

        '
      security:
      - oauth_2_0:
        - user-follow-read
  /playlists/{playlist_id}/followers/contains:
    get:
      tags:
      - Users
      operationId: check-if-user-follows-playlist
      summary: 'Check if Current User Follows Playlist

        '
      deprecated: true
      description: 'Check to see if the current user is following a specified playlist.


        **Note:** This endpoint is deprecated. Use [Check User''s Saved Items](/documentation/web-api/reference/check-library-contains) instead.

        '
      security:
      - oauth_2_0: []
components:
  securitySchemes:
    oauth_2_0:
      type: oauth2
      description: Spotify supports OAuth 2.0 for authenticating all API requests.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          tokenUrl: https://accounts.spotify.com/api/token
          scopes:
            app-remote-control: 'Communicate with the Spotify app on your device.

              '
            playlist-read-private: 'Access your private playlists.

              '
            playlist-read-collaborative: 'Access your collaborative playlists.

              '
            playlist-modify-public: 'Manage your public playlists.

              '
            playlist-modify-private: 'Manage your private playlists.

              '
            user-library-read: 'Access your saved content.

              '
            user-library-modify: 'Manage your saved content.

              '
            user-read-private: 'Access your subscription details.

              '
            user-read-email: 'Get your real email address.

              '
            user-follow-read: 'Access your followers and who you are following.

              '
            user-follow-modify: 'Manage your saved content.

              '
            user-top-read: 'Read your top artists and content.

              '
            user-read-playback-position: 'Read your position in content you have played.

              '
            user-read-playback-state: 'Read your currently playing content and Spotify Connect devices information.

              '
            user-read-recently-played: 'Access your recently played items.

              '
            user-read-currently-playing: 'Read your currently playing content.

              '
            user-modify-playback-state: 'Control playback on your Spotify clients and Spotify Connect devices.

              '
            ugc-image-upload: 'Upload images to Spotify on your behalf.

              '
            streaming: 'Play content and control playback on your other devices.

              '
