openapi: 3.2.0
info:
  description: You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more.
  version: 1.0.0
  title: Spotify Web Tracks API
  termsOfService: https://developer.spotify.com/terms/
  contact:
    name: Spotify for Developers Community
    url: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
servers:
- url: https://api.spotify.com/v1
tags:
- name: Tracks
paths:
  /tracks/{id}:
    get:
      tags:
      - Tracks
      operationId: get-track
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      summary: Get Track
      description: 'Get Spotify catalog information for a single track identified by its

        unique Spotify ID.'
      security:
      - oauth_2_0: []
  /tracks:
    get:
      deprecated: true
      tags:
      - Tracks
      operationId: get-several-tracks
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataWithMachineLearningPolicyList'
      summary: Get Several Tracks
      description: Get Spotify catalog information for multiple tracks based on their Spotify IDs.
      security:
      - oauth_2_0: []
  /me/tracks:
    get:
      tags:
      - Tracks
      operationId: get-users-saved-tracks
      summary: Get User's Saved Tracks
      description: Get a list of the songs saved in the current Spotify user's 'Your Music' library.
      security:
      - oauth_2_0:
        - user-library-read
    put:
      deprecated: true
      tags:
      - Tracks
      operationId: save-tracks-user
      summary: Save Tracks for Current User
      description: 'Save one or more tracks to the current user''s ''Your Music'' library.


        **Note:** This endpoint is deprecated. Use Save Items to Library instead.'
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      deprecated: true
      tags:
      - Tracks
      operationId: remove-tracks-user
      summary: Remove User's Saved Tracks
      description: 'Remove one or more tracks from the current user''s ''Your Music'' library.


        **Note:** This endpoint is deprecated. Use Remove Items from Library instead.'
      security:
      - oauth_2_0:
        - user-library-modify
  /me/tracks/contains:
    get:
      tags:
      - Tracks
      operationId: check-users-saved-tracks
      summary: Check User's Saved Tracks
      deprecated: true
      description: 'Check if one or more tracks is already saved in the current Spotify user''s ''Your Music'' library.


        **Note:** This endpoint is deprecated. Use Check User''s Saved Items instead.'
      security:
      - oauth_2_0:
        - user-library-read
  /audio-features:
    get:
      deprecated: true
      tags:
      - Tracks
      operationId: get-several-audio-features
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
      summary: Get Several Tracks' Audio Features
      description: Get audio features for multiple tracks based on their Spotify IDs.
      security:
      - oauth_2_0: []
  /audio-features/{id}:
    get:
      deprecated: true
      tags:
      - Tracks
      operationId: get-audio-features
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
      summary: Get Track's Audio Features
      description: 'Get audio feature information for a single track identified by its unique

        Spotify ID.'
      security:
      - oauth_2_0: []
  /audio-analysis/{id}:
    get:
      deprecated: true
      tags:
      - Tracks
      operationId: get-audio-analysis
      summary: Get Track's Audio Analysis
      description: Get a low-level audio analysis for a track in the Spotify catalog. The audio analysis describes the track’s structure and musical content, including rhythm, pitch, and timbre.
      security:
      - oauth_2_0: []
  /recommendations:
    get:
      deprecated: true
      tags:
      - Tracks
      operationId: get-recommendations
      x-spotify-policy-list:
      - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
      summary: Get Recommendations
      description: 'Recommendations are generated based on the available information for a given seed entity and matched against similar artists and tracks. If there is sufficient information about the provided seeds, a list of tracks will be returned together with pool size details.


        For artists and tracks that are very new or obscure there might not be enough data to generate a list of tracks.'
      security:
      - oauth_2_0: []
components:
  x-spotify-policy:
    metadataWithMachineLearningPolicyList:
    - $ref: '#/components/x-spotify-policy/policies/Downloading'
    - $ref: '#/components/x-spotify-policy/policies/VisualAlteration'
    - $ref: '#/components/x-spotify-policy/policies/Attribution'
    - $ref: '#/components/x-spotify-policy/policies/MachineLearning'
  securitySchemes:
    oauth_2_0:
      type: oauth2
      description: Spotify supports OAuth 2.0 for authenticating all API requests.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          tokenUrl: https://accounts.spotify.com/api/token
          scopes:
            app-remote-control: 'Communicate with the Spotify app on your device.

              '
            playlist-read-private: 'Access your private playlists.

              '
            playlist-read-collaborative: 'Access your collaborative playlists.

              '
            playlist-modify-public: 'Manage your public playlists.

              '
            playlist-modify-private: 'Manage your private playlists.

              '
            user-library-read: 'Access your saved content.

              '
            user-library-modify: 'Manage your saved content.

              '
            user-read-private: 'Access your subscription details.

              '
            user-read-email: 'Get your real email address.

              '
            user-follow-read: 'Access your followers and who you are following.

              '
            user-follow-modify: 'Manage your saved content.

              '
            user-top-read: 'Read your top artists and content.

              '
            user-read-playback-position: 'Read your position in content you have played.

              '
            user-read-playback-state: 'Read your currently playing content and Spotify Connect devices information.

              '
            user-read-recently-played: 'Access your recently played items.

              '
            user-read-currently-playing: 'Read your currently playing content.

              '
            user-modify-playback-state: 'Control playback on your Spotify clients and Spotify Connect devices.

              '
            ugc-image-upload: 'Upload images to Spotify on your behalf.

              '
            streaming: 'Play content and control playback on your other devices.

              '
