openapi: 3.0.3
info:
  description: 'You can use Spotify''s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.


    In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.


    The base URI for all Web API requests is `https://api.spotify.com/v1`.


    Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

    '
  version: 1.0.0
  title: Spotify Web Albums Shows API
  termsOfService: https://developer.spotify.com/terms/
  contact:
    name: Spotify for Developers Community
    url: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
servers:
- url: https://api.spotify.com/v1
tags:
- name: Shows
paths:
  /shows/{id}:
    get:
      tags:
      - Shows
      operationId: get-a-show
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      summary: 'Get Show

        '
      description: 'Get Spotify catalog information for a single show identified by its

        unique Spotify ID.

        '
      security:
      - oauth_2_0:
        - user-read-playback-position
  /shows:
    get:
      deprecated: true
      tags:
      - Shows
      operationId: get-multiple-shows
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      summary: 'Get Several Shows

        '
      description: 'Get Spotify catalog information for several shows based on their Spotify IDs.

        '
      security:
      - oauth_2_0: []
  /shows/{id}/episodes:
    get:
      tags:
      - Shows
      operationId: get-a-shows-episodes
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      summary: 'Get Show Episodes

        '
      description: 'Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.

        '
      security:
      - oauth_2_0:
        - user-read-playback-position
  /me/shows:
    get:
      tags:
      - Shows
      operationId: get-users-saved-shows
      summary: 'Get User''s Saved Shows

        '
      description: 'Get a list of shows saved in the current Spotify user''s library. Optional parameters can be used to limit the number of shows returned.

        '
      security:
      - oauth_2_0:
        - user-library-read
    put:
      deprecated: true
      tags:
      - Shows
      operationId: save-shows-user
      summary: 'Save Shows for Current User

        '
      description: 'Save one or more shows to current Spotify user''s library.


        **Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
    delete:
      deprecated: true
      tags:
      - Shows
      operationId: remove-shows-user
      summary: 'Remove User''s Saved Shows

        '
      description: 'Delete one or more shows from current Spotify user''s library.


        **Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-library-modify
  /me/shows/contains:
    get:
      tags:
      - Shows
      operationId: check-users-saved-shows
      summary: 'Check User''s Saved Shows

        '
      deprecated: true
      description: 'Check if one or more shows is already saved in the current Spotify user''s library.


        **Note:** This endpoint is deprecated. Use [Check User''s Saved Items](/documentation/web-api/reference/check-library-contains) instead.

        '
      security:
      - oauth_2_0:
        - user-library-read
components:
  x-spotify-policy:
    metadataPolicyList:
    - $ref: '#/components/x-spotify-policy/policies/Downloading'
    - $ref: '#/components/x-spotify-policy/policies/VisualAlteration'
    - $ref: '#/components/x-spotify-policy/policies/Attribution'
  securitySchemes:
    oauth_2_0:
      type: oauth2
      description: Spotify supports OAuth 2.0 for authenticating all API requests.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          tokenUrl: https://accounts.spotify.com/api/token
          scopes:
            app-remote-control: 'Communicate with the Spotify app on your device.

              '
            playlist-read-private: 'Access your private playlists.

              '
            playlist-read-collaborative: 'Access your collaborative playlists.

              '
            playlist-modify-public: 'Manage your public playlists.

              '
            playlist-modify-private: 'Manage your private playlists.

              '
            user-library-read: 'Access your saved content.

              '
            user-library-modify: 'Manage your saved content.

              '
            user-read-private: 'Access your subscription details.

              '
            user-read-email: 'Get your real email address.

              '
            user-follow-read: 'Access your followers and who you are following.

              '
            user-follow-modify: 'Manage your saved content.

              '
            user-top-read: 'Read your top artists and content.

              '
            user-read-playback-position: 'Read your position in content you have played.

              '
            user-read-playback-state: 'Read your currently playing content and Spotify Connect devices information.

              '
            user-read-recently-played: 'Access your recently played items.

              '
            user-read-currently-playing: 'Read your currently playing content.

              '
            user-modify-playback-state: 'Control playback on your Spotify clients and Spotify Connect devices.

              '
            ugc-image-upload: 'Upload images to Spotify on your behalf.

              '
            streaming: 'Play content and control playback on your other devices.

              '
