openapi: 3.0.3
info:
  description: 'You can use Spotify''s Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.


    In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.


    The base URI for all Web API requests is `https://api.spotify.com/v1`.


    Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

    '
  version: 1.0.0
  title: Spotify Web Albums Artists API
  termsOfService: https://developer.spotify.com/terms/
  contact:
    name: Spotify for Developers Community
    url: https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer
servers:
- url: https://api.spotify.com/v1
tags:
- name: Artists
paths:
  /artists/{id}:
    get:
      tags:
      - Artists
      operationId: get-an-artist
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      summary: 'Get Artist

        '
      description: 'Get Spotify catalog information for a single artist identified by their unique Spotify ID.

        '
      security:
      - oauth_2_0: []
  /artists:
    get:
      deprecated: true
      tags:
      - Artists
      operationId: get-multiple-artists
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      summary: 'Get Several Artists

        '
      description: 'Get Spotify catalog information for several artists based on their Spotify IDs.

        '
      security:
      - oauth_2_0: []
  /artists/{id}/albums:
    get:
      tags:
      - Artists
      operationId: get-an-artists-albums
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      summary: 'Get Artist''s Albums

        '
      description: 'Get Spotify catalog information about an artist''s albums.

        '
      security:
      - oauth_2_0: []
  /artists/{id}/top-tracks:
    get:
      deprecated: true
      tags:
      - Artists
      operationId: get-an-artists-top-tracks
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      summary: 'Get Artist''s Top Tracks

        '
      description: 'Get Spotify catalog information about an artist''s top tracks by country.

        '
      security:
      - oauth_2_0: []
  /artists/{id}/related-artists:
    get:
      deprecated: true
      tags:
      - Artists
      operationId: get-an-artists-related-artists
      x-spotify-policy-list:
        $ref: '#/components/x-spotify-policy/metadataPolicyList'
      summary: 'Get Artist''s Related Artists

        '
      description: 'Get Spotify catalog information about artists similar to a given artist. Similarity is based on analysis of the Spotify community''s listening history.

        '
      security:
      - oauth_2_0: []
  /me/following:
    get:
      tags:
      - Artists
      operationId: get-followed
      summary: 'Get Followed Artists

        '
      description: 'Get the current user''s followed artists.

        '
      security:
      - oauth_2_0:
        - user-follow-read
    put:
      deprecated: true
      tags:
      - Artists
      operationId: follow-artists-users
      summary: 'Follow Artists or Users

        '
      description: 'Add the current user as a follower of one or more artists or other Spotify users.


        **Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-follow-modify
    delete:
      deprecated: true
      tags:
      - Artists
      operationId: unfollow-artists-users
      summary: 'Unfollow Artists or Users

        '
      description: 'Remove the current user as a follower of one or more artists or other Spotify users.


        **Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.

        '
      security:
      - oauth_2_0:
        - user-follow-modify
  /me/following/contains:
    get:
      tags:
      - Artists
      operationId: check-current-user-follows
      summary: 'Check If User Follows Artists or Users

        '
      deprecated: true
      description: 'Check to see if the current user is following one or more artists or other Spotify users.


        **Note:** This endpoint is deprecated. Use [Check User''s Saved Items](/documentation/web-api/reference/check-library-contains) instead.

        '
      security:
      - oauth_2_0:
        - user-follow-read
components:
  x-spotify-policy:
    metadataPolicyList:
    - $ref: '#/components/x-spotify-policy/policies/Downloading'
    - $ref: '#/components/x-spotify-policy/policies/VisualAlteration'
    - $ref: '#/components/x-spotify-policy/policies/Attribution'
  securitySchemes:
    oauth_2_0:
      type: oauth2
      description: Spotify supports OAuth 2.0 for authenticating all API requests.
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          tokenUrl: https://accounts.spotify.com/api/token
          scopes:
            app-remote-control: 'Communicate with the Spotify app on your device.

              '
            playlist-read-private: 'Access your private playlists.

              '
            playlist-read-collaborative: 'Access your collaborative playlists.

              '
            playlist-modify-public: 'Manage your public playlists.

              '
            playlist-modify-private: 'Manage your private playlists.

              '
            user-library-read: 'Access your saved content.

              '
            user-library-modify: 'Manage your saved content.

              '
            user-read-private: 'Access your subscription details.

              '
            user-read-email: 'Get your real email address.

              '
            user-follow-read: 'Access your followers and who you are following.

              '
            user-follow-modify: 'Manage your saved content.

              '
            user-top-read: 'Read your top artists and content.

              '
            user-read-playback-position: 'Read your position in content you have played.

              '
            user-read-playback-state: 'Read your currently playing content and Spotify Connect devices information.

              '
            user-read-recently-played: 'Access your recently played items.

              '
            user-read-currently-playing: 'Read your currently playing content.

              '
            user-modify-playback-state: 'Control playback on your Spotify clients and Spotify Connect devices.

              '
            ugc-image-upload: 'Upload images to Spotify on your behalf.

              '
            streaming: 'Play content and control playback on your other devices.

              '
